name: deploy-coffee-shop-api


on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      # 🚨 CORRECCIÓN: Quitamos el 'working-directory' porque package.json está en la raíz
      run: npm install
      
    - name: Install Serverless Framework
      run: npm install -g serverless
      
    - name: Deploy to AWS (Dev)
      if: github.ref == 'refs/heads/dev'
      # 🚨 CORRECCIÓN: Ejecutamos el despliegue desde la raíz, sin CD ni --config
      run: npx serverless deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Deploy to AWS (Prod)
      if: github.ref == 'refs_heads/main'
      # 🚨 CORRECCIÓN: Ejecutamos el despliegue desde la raíz, sin CD ni --config
      run: npx serverless deploy --stage prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

